# Caseless Rifle

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineCaselessRifleFMJ
  result: MagazineCaselessRifleFMJ
  materials:
    Steel: 350

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineCaselessRifleShortFMJ
  result: MagazineCaselessRifleShortFMJ
  materials:
    Steel: 300

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineCaselessRifleIncendiary
  result: MagazineCaselessRifleIncendiary
  materials:
    Plastic: 350

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineCaselessRiflePractice
  result: MagazineCaselessRiflePractice
  materials:
    Steel: 250

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineCaselessRifleUranium
  result: MagazineCaselessRifleUranium
  materials:
    Uranium: 350

# Caseless Rifle Short

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineCaselessRifleShort
  result: MagazineCaselessRifleShort
  materials:
    Steel: 250

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineCaselessRifleShortPractice
  result: MagazineCaselessRifleShortPractice
  materials:
    Steel: 150

# Magazine boxes

# Caseless Rifle

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxCaselessRifleFMJ
  result: MagazineBoxCaselessRifleFMJ
  materials:
    Steel: 720

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxCaselessRifleIncendiary
  result: MagazineBoxCaselessRifleIncendiary
  materials:
    Plastic: 720

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxCaselessRiflePractice
  result: MagazineBoxCaselessRiflePractice
  materials:
    Steel: 500

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineBoxCaselessRifleUranium
  result: MagazineBoxCaselessRifleUranium
  materials:
    Uranium: 720

- type: latheRecipe
  id: CartridgeArith
  result: CartridgeArith
  completetime: 1
  materials:
    Glass: 100
    Plasma: 100

- type: latheRecipe
  id: CartridgeDylo
  result: CartridgeDylo
  completetime: 1
  materials:
    Glass: 100
    Plasma: 100

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineMagnumLeverRifleEmpty
  result: MagazineMagnumLeverRifleEmpty
  materials:
    Steel: 25

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineMagnumLeverRifle
  result: MagazineMagnumLeverRifle
  materials:
    Steel: 185

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineClipM1GarandEmpty
  result: MagazineClipM1GarandEmpty
  materials:
    Steel: 12

- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineClipM1Garand
  result: MagazineClipM1Garand
  materials:
    Steel: 150
